//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProductDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetails
    {
        public int DeliveryDetailID { get; set; }
        public int DeliveryID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
    
        public virtual Deliveries Deliveries { get; set; }
        public virtual Products Products { get; set; }
    }
}
