//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProductDelivery
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAdmins
    {
        public int id { get; set; }
        public string admin_login { get; set; }
        public string admin_password { get; set; }
        public string email { get; set; }
        public string Position { get; set; }
    }
}
